name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    
    - name: Set up Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91fb8d2507d9949662 # v2
      
    - name: Build and Test
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4
      with:
        arguments: clean check
        
    - name: Upload Test Reports
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f34369b2 # v4
      if: always()
      with:
        name: test-reports-${{ matrix.os }}
        path: '**/build/reports/tests/'
